### PR TITLE
Allow custom linebreaks in cards via <br> syntax

### PR DESCRIPTION
**Pull request by TerminalMan**
Hi again,

I'm not 100% sure this is rock solid, so far i didn't manage to break anything with it, but you might want to unleash it on a testdeck first :p

The string modification only acts on the temp string "s2" in the prettyPrint function, thus it shouldn't have any effect outside of prettyPrint().

usage: nao a "deckname" "line1\<br>line2" "line1\<br>line2"

### CODE REVIEW

**Comment by gRastello** [comment]
I understand that having line breaks can be useful however your approach breaks unicode support. Try the following:
```
$ nao add deck "ただご評でいうてはならんのうて" "あなたのお創設も若い得下さろるた。"
$ nao review deck
```
and you'll get completely unreadable text. I know that not everyone wants unicode in their flashcards but I'd like to maintain this feature also considering that I wrote Nao with the intent of using it to learn some Japanese vocabulary in the first place.

Line breaks however can be useful so if you can manage to get them working while preserving unicode characters I'd be glad to include that feature. Unfortunately I can't really work on it right now 'cause exams.

**Comment by TerminalMan** [comment]
Good thing you noticed it, I think Unicode is absolutely mandatory. The trick was to use 'rune'. I will post another pull request soon.

私も日本語を勉強している。。。時々~

**Comment by gRastello** [comment]
Characters aren't corrupted anymore but in seems that now lines can extend over LINELENGTH because the function does not consider the rune's width. I also found a similar character-corrupting bug in the current version of Nao that can be pointed back to the same rune width problem. My suggestion is then to tackle the problem by using the [unicode/utf8](https://golang.org/pkg/unicode/utf8/) package; looping over strings with `DecodeRuneInString` seems a promising approach to me.

**Comment by TerminalMan** [comment]
`
import (
    "fmt"
    "go-runewidth"
)

func main() {
    string := "ひらがな hiragana"

    for _, rune := range string {
        fmt.Printf("%c", rune)
        rune_visualwidth := runewidth.RuneWidth(rune)
        fmt.Printf("\t -> %d \n", rune_visualwidth)
    }   

}
`

That way we can avoid the "unicode/utf8"
But getting around the go-runewidth library seems difficult.

**Comment by gRastello** [comment]
Well I guess using `go-runewidth` is the only way to get this thing to work as indented. I'm not against using `go-runewidth` since avoiding it will probably require to write an equivalent from scratch.

**Pull request closed without merging**
